version: '2'
services:
  sdnops:
    image: sdnops
    environment:
      - Surveyor=126.179.10.10,126.179.10.13,126.179.10.16
      - INT_VIP=126.179.10.7
      - FQDN=archcncm0576.cluster1
      - AUTH_PORT=6000
      - WEB_PORT=7787
      - MQ_PORT=7788
      - NODE_MODE=survey
      #- NODE_MODE=respondent
    privileged: true
    network_mode: "host"
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/containers:/var/lib/containers
      - /etc/hosts:/etc/hosts
      - /usr/bin:/host/usr/bin
      - /bin:/host/bin
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/sysctl.d:/etc/sysctl.d
      - /var/log/sdn:/var/log/sdn
      - /etc/sysconfig/network-scripts:/etc/sysconfig/network-scripts
    restart: always
    stdin_open: True
    tty: True
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
